# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 300)
        MainWindow.setMinimumSize(QtCore.QSize(512, 300))
        MainWindow.setMaximumSize(QtCore.QSize(512, 300))
        MainWindow.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.linkOne = QtWidgets.QLineEdit(self.centralwidget)
        self.linkOne.setGeometry(QtCore.QRect(20, 20, 301, 20))
        self.linkOne.setStyleSheet("color: rgb(255, 255, 255);")
        self.linkOne.setObjectName("linkOne")
        self.linkTwo = QtWidgets.QLineEdit(self.centralwidget)
        self.linkTwo.setGeometry(QtCore.QRect(20, 70, 301, 20))
        self.linkTwo.setStyleSheet("color: rgb(255, 255, 255);")
        self.linkTwo.setObjectName("linkTwo")
        self.linkFinal = QtWidgets.QLineEdit(self.centralwidget)
        self.linkFinal.setGeometry(QtCore.QRect(20, 120, 301, 20))
        self.linkFinal.setStyleSheet("color: rgb(255, 255, 255);")
        self.linkFinal.setObjectName("linkFinal")
        self.calculaterNft = QtWidgets.QPushButton(self.centralwidget)
        self.calculaterNft.setGeometry(QtCore.QRect(20, 170, 75, 23))
        self.calculaterNft.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.calculaterNft.setObjectName("calculaterNft")
        self.generatorNgt = QtWidgets.QPushButton(self.centralwidget)
        self.generatorNgt.setGeometry(QtCore.QRect(110, 170, 91, 23))
        self.generatorNgt.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.generatorNgt.setObjectName("generatorNgt")
        self.consoleTxt = QtWidgets.QLabel(self.centralwidget)
        self.consoleTxt.setGeometry(QtCore.QRect(0, 280, 521, 21))
        self.consoleTxt.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"padding-left: 10px;")
        self.consoleTxt.setObjectName("consoleTxt")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 20, 47, 13))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 70, 47, 13))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 120, 47, 13))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.timeGN = QtWidgets.QLabel(self.centralwidget)
        self.timeGN.setGeometry(QtCore.QRect(20, 200, 47, 13))
        self.timeGN.setStyleSheet("color: rgb(255, 255, 255);")
        self.timeGN.setObjectName("timeGN")
        self.itemGN = QtWidgets.QLabel(self.centralwidget)
        self.itemGN.setGeometry(QtCore.QRect(20, 220, 47, 13))
        self.itemGN.setStyleSheet("color: rgb(255, 255, 255);")
        self.itemGN.setObjectName("itemGN")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calculaterNft.setText(_translate("MainWindow", "Посчитать"))
        self.generatorNgt.setText(_translate("MainWindow", "Генерировать"))
        self.consoleTxt.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "link 1"))
        self.label_3.setText(_translate("MainWindow", "link 2"))
        self.label_4.setText(_translate("MainWindow", "final"))
        self.timeGN.setText(_translate("MainWindow", "0"))
        self.itemGN.setText(_translate("MainWindow", "0"))
